name: Build and Release Firmware

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:v5.2.1
    strategy:
      fail-fast: false
      matrix:
        target:
          - { chip: 'esp32', boot_offset: '0x1000', ota_dir: 'ESP32' }
          - { chip: 'esp32c3', boot_offset: '0x0', ota_dir: 'ESP32-C3' }
          - { chip: 'esp32s2', boot_offset: '0x1000', ota_dir: 'ESP32-S2' }
          - { chip: 'esp32s3', boot_offset: '0x0', ota_dir: 'ESP32-S3' }
          - { chip: 'esp32c6', boot_offset: '0x0', ota_dir: 'ESP32-C6' }

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fix git ownership
        run: git config --global --add safe.directory ${{ github.workspace }}

      - name: Set VERSION environment variable from file
        run: echo "VERSION=$(head -1 version)" >> $GITHUB_ENV

      - name: Update firmware version in source files
        run: |
          sed -i -e 's/DEV-VERSION/${{ env.VERSION }}/g' CMakeLists.txt

      - name: Minify HTML files
        run: |
          apt-get update && apt-get install -y python3-pip
          pip3 install htmlmin
          python3 .github/workflows/shrinkHTML.py
        shell: sh

      - name: Build firmware for ${{ matrix.target.chip }}
        run: |
          . /opt/esp/idf/export.sh
          idf.py set-target ${{ matrix.target.chip }}
          idf.py build

      - name: List build directory
        run: ls -R build

      - name: Create combined binary for ${{ matrix.target.chip }}
        run: |
          . /opt/esp/idf/export.sh
          folder="build"
          chip="${{ matrix.target.chip }}"
          version="${{ env.VERSION }}"
          boot_offset="${{ matrix.target.boot_offset }}"
          
          mkdir -p release/zips
          mkdir -p release/ota/${{ matrix.target.ota_dir }}

          cp version release/ota/
          cp $folder/firmware.bin release/ota/${{ matrix.target.ota_dir }}/firmware.bin
          mv $folder/firmware.bin $folder/${chip}_gpio_debugger_v${version}.bin
          
          esptool.py --chip $chip merge_bin -o $folder/${chip}_gpio_debugger_full_v${version}.bin --flash_mode keep --flash_freq keep --flash_size keep $boot_offset $folder/bootloader/bootloader.bin 0x10000 $folder/${chip}_gpio_debugger_v${version}.bin 0x8000 $folder/partition_table/partition-table.bin
          
          zip -j release/zips/${chip}_gpio_debugger_update_v${version}.zip $folder/${chip}_gpio_debugger_v${version}.bin
          zip -j release/zips/${chip}_gpio_debugger_full_v${version}.zip $folder/${chip}_gpio_debugger_full_v${version}.bin

      - name: Upload firmware zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware-zips-${{ matrix.target.chip }}
          path: release/zips/*.zip

      - name: Upload OTA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ota-files-${{ matrix.target.chip }}
          path: release/ota/

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set VERSION environment variable from file
        run: echo "VERSION=$(head -1 version)" >> $GITHUB_ENV

      - name: Check if Git tag already exists
        run: |
          TAG="v${{ env.VERSION }}"
          if git show-ref --tags --verify --quiet "refs/tags/${TAG}" && [[ "${TAG}" != *"DEV"* ]]; then
            echo "Error: Tag ${TAG} already exists."
            exit 1
          fi

      - name: Download all firmware artifacts
        uses: actions/download-artifact@v4
        with:
          path: release_artifacts
      
      - name: Organize downloaded artifacts
        run: |
          mkdir -p release_final
          find release_artifacts -name "*.zip" -exec mv {} release_final/ \;

      - name: Create draft release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          draft: true
          automatic_release_tag: v${{ env.VERSION }}
          title: v${{ env.VERSION }}
          files: |
            release_final/*.zip

      - name: Create changelog from version file
        run: tail -n +3 version | sed 's/^/- /' > changelog

      - name: Update release with changelog
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: v${{ env.VERSION }}
          tag: v${{ env.VERSION }}
          draft: true
          bodyFile: "changelog"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/master'
    steps:
      - name: Download all OTA artifacts
        uses: actions/download-artifact@v4
        with:
          path: ota_artifacts
      
      - name: Assemble final OTA directory
        run: |
          mkdir -p final_ota_dir
          find ota_artifacts -mindepth 1 -maxdepth 1 -type d | while read -r dir; do
            cp -r "$dir"/* final_ota_dir/
          done

      - name: Set release branch for dev
        if: github.ref == 'refs/heads/dev'
        run: echo "RELEASE_BRANCH=releases-staging" >> $GITHUB_ENV

      - name: Set release branch for master
        if: github.ref == 'refs/heads/master'
        run: echo "RELEASE_BRANCH=releases-production" >> $GITHUB_ENV

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: final_ota_dir
          branch: ${{ env.RELEASE_BRANCH }}
